# SpringBoot自动注入属性 https://docs.spring.io/spring-boot/docs/1.5.11.BUILD-SNAPSHOT/reference/htmlsingle/#common-application-properties

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/shop
  username: root
  password: password
  driver-class-name: # Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: create

# SOLR (SolrProperties)
spring.data.solr:
  host: http://127.0.0.1:8983/solr # Solr host. Ignored if "zk-host" is set.
  repositories.enabled: true # Enable Solr repositories.
  zk-host: # ZooKeeper host address in the form HOST:PORT.